## Site author's information.
author:
  name:      Alberto Pe√±a Abril
  title:     Software Craftsmanship
  email:     plagelao@gmail.com
  site:      http://plagelao.github.com
  location:  "Woking, UK"
  gh:
    user:    plagelao
  twitter:   plagelao

permalink:  /:year/:month/:title
server: true
pygments: true
auto: true
url: http://plagelao.github.com
